version: "3.9"

volumes:
   sarah-connor:
   boen:
  #  silberman-images:


services:

  Temuera:
    image: boba-fett/temuera
    build:
      context: ./Boba-Fett/Temuera
    ports:
      - 3311:8080
    depends_on:
      - Sarah-Connor

  Thrain:
    image: mariadb
    command: --max-allowed-packet=256M
    environment:
      MYSQL_DATABASE: wikipedia
      MYSQL_USER: wikipedia
      MYSQL_PASSWORD: wikipedia
      MYSQL_ROOT_PASSWORD: wikipedia
    volumes:
      - boen:/var/lib/mysql

  Silberman:
    image: lang/silberman
    build:
      context: ./Boba-Fett/Silberman
    ports:
      - 8000:80
    depends_on:
      - Thrain
    links:
      - Thrain
    # volumes:
    #   - silberman-images:/var/www/html/images
    #   - ./Boba-Fett/Silberman/LocalSettings.php:/var/www/html/LocalSettings.php
    #   - ./Boba-Fett/Silberman/extensions/TemplateStyles:/var/www/html/extensions/TemplateStyles
    #   - ./Boba-Fett/Silberman/extensions/Scribunto:/var/www/html/extensions/Scribunto
    #   - ./Boba-Fett/Silberman/php.ini:/usr/local/etc/php/conf.d/mediawiki.ini